# Generated by Django 4.1.4 on 2022-12-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('m3_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('nots', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('start_Date', models.DateField(auto_now_add=True)),
                ('finish_Date', models.DateField(auto_now_add=True)),
                ('number_Of_Days', models.IntegerField()),
                ('number_Of_Hours', models.IntegerField()),
                ('production_Ratio', models.IntegerField()),
                ('nots', models.TextField(blank=True, null=True)),
                ('project_Job_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studens.job_type')),
                ('project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studens.projects')),
                ('project_Stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studens.stages')),
            ],
        ),
    ]
