# Generated by Django 4.1.4 on 2022-12-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='production_Ratio',
        ),
        migrations.AlterField(
            model_name='job_type',
            name='m3_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='finish_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='number_Of_Days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='number_Of_Hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_Date',
            field=models.DateField(),
        ),
    ]
