# Generated by Django 4.1.4 on 2022-12-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0002_remove_mission_production_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='unit',
            field=models.CharField(blank=True, choices=[('طابوقة', 'طابوقة')], max_length=10),
        ),
    ]
