# Generated by Django 4.1.4 on 2022-12-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0004_alter_mission_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='unit',
            field=models.CharField(choices=[('1', 'متر مكعب'), ('2', 'طابوقة')], max_length=1),
        ),
    ]
