# Generated by Django 4.1.4 on 2022-12-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0005_alter_mission_quantity_alter_mission_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='number_Of_Days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='number_Of_Hours',
            field=models.IntegerField(),
        ),
    ]
