# Generated by Django 4.1.4 on 2023-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0006_alter_mission_number_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(),
        ),
    ]
